"""'added_about_author_colum

Revision ID: 2a5d087da922
Revises: 27e131d44064
Create Date: 2022-08-14 19:21:55.629233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5d087da922'
down_revision = '27e131d44064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_model', sa.Column('about_author', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_model', 'about_author')
    # ### end Alembic commands ###
